services:
  trainerdb:
    container_name: trainerdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  trainerservice.api:
    container_name: trainerservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://trainerdb:27017"
    depends_on:
      - trainerdb
    ports:
      - "8000:8080"
