services:
  trainerdb:
    container_name: trainerdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  mssql:
    container_name: mssql
    environment:
      - SA_PASSWORD=MATF12345678rs2
      - ACCEPT_EULA=Y 
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data 

  trainerservice.api:
    container_name: trainerservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://trainerdb:27017"
    depends_on:
      - trainerdb
    ports:
      - "8000:8080"

  clientservice.api:
    container_name: clientservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=True;Encrypt=False;"
    depends_on:
      - mssql
    ports:
      - "4000:8080"
