services:
  trainerdb:
    image: mongo
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest

  trainerservice.api:
    image: ${DOCKER_REGISTRY-}trainerserviceapi
    build:
      context: .
      dockerfile: Services/TrainerService/TrainerService.API/Dockerfile
  
  clientservice.api:
    image: ${DOCKER_REGISTRY-}clientserviceapi
    build:
      context: .
      dockerfile: Services/ClientService/ClientService.API/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile

volumes:
  mongo_data:
  mssql_data:
