services:
  trainerdb:
    container_name: trainerdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - trainermongo_data:/data/db


  clientdb:
    container_name: clientdb
    restart: always
    ports:
    - 27019:27017
    volumes: 
    - clientmongo_data:/data/db

  reviewdb:
    container_name: reviewdb
    restart: always
    ports:
      - 27018:27017
    volumes:
      - reviewmongo_data:/data/db

  mssql:
    container_name: mssql
    environment:
      - SA_PASSWORD=MATF12345678rs2
      - ACCEPT_EULA=Y 
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data 

  trainerservice.api:
    container_name: trainerservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://trainerdb:27017"
      - "GrpcSettings:ReviewUrl=http://host.docker.internal:8002"
    depends_on:
      - trainerdb
    ports:
      - "8000:8080"

  clientservice.api:
    container_name: clientservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://clientdb:27017" 
    ports:
      - "8100:8080"

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=True;Encrypt=False;"
    depends_on:
      - mssql
    ports:
      - "4000:8080"

  reviewservice.api:
    container_name: reviewservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://reviewdb:27017"
    depends_on:
      - reviewdb
    ports:
      - "8001:8080"


  reviewservice.grpc:
    container_name: reviewservice.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://reviewdb:27017"
    depends_on:
      - reviewdb
    ports:
      - "8002:8080"
