services:
  trainerdb:
    image: mongo
  reviewdb:
    image: mongo

  trainerservice.api:
    image: ${DOCKER_REGISTRY-}trainerserviceapi
    build:
      context: .
      dockerfile: Services/TrainerService/TrainerService.API/Dockerfile
  
  clientservice.api:
    image: ${DOCKER_REGISTRY-}clientserviceapi
    build:
      context: .
      dockerfile: Services/ClientService/ClientService.API/Dockerfile

  reviewservice.api:
    image: ${DOCKER_REGISTRY-}reviewserviceapi
    build:
      context: .
      dockerfile: Services/ReviewService/ReviewService.API/Dockerfile

volumes:
  trainermongo_data:
  reviewmongo_data:

