services:
  trainerdb:
    image: mongo
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest

  clientdb:
    image: mongo

  reviewdb:
    image: mongo

  trainerservice.api:
    image: ${DOCKER_REGISTRY-}trainerserviceapi
    build:
      context: .
      dockerfile: Services/TrainerService/TrainerService.API/Dockerfile
  
  clientservice.api:
    image: ${DOCKER_REGISTRY-}clientserviceapi
    build:
      context: .
      dockerfile: Services/ClientService/ClientService.API/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile

  reviewservice.api:
    image: ${DOCKER_REGISTRY-}reviewserviceapi
    build:
      context: .
      dockerfile: Services/ReviewService/ReviewService.API/Dockerfile

  reviewservice.grpc:
    image: ${DOCKER_REGISTRY-}reviewservicegrpc
    build:
      context: .
      dockerfile: Services/ReviewService/ReviewService.GRPC/Dockerfile

volumes:
  trainermongo_data:
  reviewmongo_data:
  clientmongo_data:
  mssql_data:

